version: '3'
services:
  postgres:
    restart: always
    image: postgres:16
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    restart: always
    image: ${REGISTRY_URL}/merchbot-backend:latest
    command: bash -c "rm -f tmp/pids/server.pid && RAILS_ENV=production bundle exec rails db:prepare && RAILS_ENV=production bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - uploads:/merchbot_backend/public/uploads
    env_file: .env
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - postgres

  redis:
    image: redis:latest
    restart: always
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  postgres_data:
  uploads: