---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/forms/{id}":
    get:
      summary: Retrieves a form
      tags:
      - Forms
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: form found
  "/forms":
    post:
      summary: Creates a form confirmation
      tags:
      - Forms
      parameters: []
      responses:
        '200':
          description: form confirmation created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                bot_id:
                  type: integer
                user_telegram_id:
                  type: string
                username:
                  type: string
                first_name:
                  type: string
                last_name:
                  type: string
                form_answers_attributes:
                  type: array
                  items:
                    type: object
                    properties:
                      question_id:
                        type: integer
                      answer:
                        type: string
              required:
              - bot_id
              - user_telegram_id
              - form_answers_attributes
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
