default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV.fetch('POSTGRES_DATABASE', 'procrastinator_ai_bot') %>
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', '') %>
  port: <%= ENV.fetch('POSTGRES_PORT', 5432) %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  host: <%= ENV.fetch('POSTGRES_HOST', 'postgres') %>
